spring:
    application:
        name: deal
    jpa:
        hibernate:
            ddl-auto: validate
    datasource:
        url: ${URL_DB:jdbc:postgresql://localhost:5432/test}
        username: ${USER_DB:test}
        password: ${PASSWORD_DB:test}
        driver-class-name: org.postgresql.Driver
    liquibase:
        enabled: true
        change-log: classpath:db/changelog/db.changelog-master.xml
    kafka:
        bootstrap-servers: ${KAFKA_SERVERS:localhost:29092}
        producer:
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
        topics:
            finish-registration:
                name: finish-registration
                partitions: 3
                replicas: 1
            create-documents:
                name: create-documents
                partitions: 3
                replicas: 1
            send-documents:
                name: send-documents
                partitions: 3
                replicas: 1
            send-ses:
                name: send-ses
                partitions: 3
                replicas: 1
            credit-issued:
                name: credit-issued
                partitions: 3
                replicas: 1
            statement-denied:
                name: statement-denied
                partitions: 3
                replicas: 1
    email:
        themes:
            finish_registration: ${FINISH_REGISTRATION_TEXT:Пожалуйста, завершите оформление заявки в личном кабинете на сайте или в мобильном приложении.}
            registration_documents: ${REGISTRATION_DOCUMENTS_TEXT:Ваша заявка сформирована. Пожалуйста, продолжите оформление документов на сайте или в мобильном приложении.}
            document_created: ${DOCUMENT_CREATED_TEXT:Документы по вашей заявке были сформированы. Ознакомится и подписать их можно в личном кабинете.}
            sign_documents: ${SIGN_DOCUMENTS_TEXT:Для завершения подпишите документы в личном кабинете, код ПЭП - }
            credit_issued: ${CREDIT_ISSUED_TEXT:Кредит одобрен, деньги поступят на указанный счет в течение 10 минут}
springdoc:
    swagger-ui:
        url: /openapi.yaml
server:
    port: ${PORT:8081}
services:
    calculator:
        base-url: ${CALCULATOR_ADDRESS:http://localhost:8080}
        offers-api: /calculator/offers
        calc-api: /calculator/calc
logging:
    pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    level:
        root: INFO
