spring:
    application:
        name: statement
server:
    port: ${PORT:8082}
services:
    deal:
        base-url: ${DEAL_ADDRESS:http://localhost:8081}
        statement-api: /deal/statement
        select-api: /deal/offer/select
allowed-services:
    gateway: ${GATEWAY_ADDRESS:http://localhost:8083}
springdoc:
    swagger-ui:
        url: /openapi.yaml
logging:
    pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    level:
        root: INFO
