spring:
    application:
        name: statement
server:
    port: 8082
services:
    deal:
        base-url: http://localhost:8081
        statement-api: /deal/statement
        select-api: /deal/offer/select
springdoc:
    swagger-ui:
        url: /openapi.yaml
logging:
    pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    level:
        root: INFO
