spring:
    application:
        name: gateway
server:
    port: ${PORT:8083}
springdoc:
    swagger-ui:
        url: /openapi.yaml
services:
    deal:
        base-url: ${DEAL_ADDRESS:http://localhost:8081}
        complete-registration-api: /deal/calculate/{statementId}
        send-documents-api: /deal/document/{statementId}/send
        sign-documents-api: /deal/document/{statementId}/sign
        code-documents-api: /deal/document/{statementId}/code
        get-statement-api: /deal/admin/statement/{statementId}
        update-statement-api: /deal/admin/statement/{statementId}/status
    statement:
        base-url: ${STATEMENT_ADDRESS:http://localhost:8082}
        process-statement-api: /statement
        select-offer-api: /statement/offer
logging:
    pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    level:
        root: INFO
