spring:
    application:
        name: gateway
server:
    port: 8083
springdoc:
    swagger-ui:
        url: /openapi.yaml
services:
    deal:
        base-url: http://localhost:8081
        complete-registration-api: /deal/calculate/{statementId}
        send-documents-api: /deal/{statementId}/send
        sign-documents-api: /deal/{statementId}/sign
        code-documents-api: /deal/{statementId}/code
    statement:
        base-url: http://localhost:8082
        process-statement-api: /statement
        select-offer-api: /statement/offer
