openapi: 3.1.0
info:
    title: Deal API
    version: 1.0.0
components:
    schemas:
        LoanStatementRequestDto:
            type: object
            properties:
                amount:
                    type: number
                    example: 150000
                term:
                    type: integer
                    format: int32
                    example: 12
                firstName:
                    type: string
                    example: Иван
                lastName:
                    type: string
                    example: Иванов
                middleName:
                    type: string
                    example: Иванович
                email:
                    type: string
                    example: 3J7wI@example.com
                birthDate:
                    type: string
                    format: date
                    example: 2000-01-01
                passportSeries:
                    type: string
                    example: 1234
                passportNumber:
                    type: string
                    example: 123456

        LoanOfferDto:
            type: object
            properties:
                statementId:
                    type: string
                    format: uuid
                requestedAmount:
                    type: number
                totalAmount:
                    type: number
                term:
                    type: integer
                    format: int32
                monthlyPayment:
                    type: number
                rate:
                    type: number
                isInsuranceEnabled:
                    type: boolean
                isSalaryClient:
                    type: boolean