spring:
    application:
        name: calculator
loan:
    base-rate: 15.0
    insurance-discount: 3.0
    salary-client-discount: 1.0
    insurance-cost-percent: 5.0
springdoc:
    swagger-ui:
        url: /openapi.yaml
logging:
    pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    level:
        root: INFO
allowed-services:
    deal: ${DEAL_ADDRESS:http://localhost:8081}
server:
    port: ${PORT:8080}
