spring:
    application:
        name: dossier
    kafka:
        bootstrap-servers: ${KAFKA_SERVERS:localhost:29092}
        consumer:
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
            group-id: deal-event-handlers
            properties:
                "[spring.json.trusted.packages]": "*"
                "[spring.deserializer.value.delegate.class]": org.springframework.kafka.support.serializer.JsonDeserializer

    mail:
        username: ${MAIL_USERNAME}
        password: ${MAIL_PASSWORD}
        host: smtp.yandex.ru
        port: 465
        protocol: smtps
        test-connection: true
server:
    port: ${PORT:8083}
logging:
    pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    level:
        root: INFO
